org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false

# Minecraft / NeoForge
minecraft_version=1.21.1
neoforge_version=21.1.248

# Parchment mappings
parchment_minecraft=1.21
parchment_mappings=2024.07.28

# Mod properties
mod_version=1.4.2
maven_group=com.breakinblocks.neosync
archives_base_name=NeoSync
mod_id=neosync
mod_author=BreakinBlocks

# Dependencies
mixinextras_version=0.4.1

# Integration deps
jei_version=19.27.0.340
jade_version=15.10.5+neoforge
sable_version=1.2.2
sable_companion_version=1.6.0
curios_version=9.5.1+1.21.1

# Publishing
curseforge_project_id=1521718
modrinth_project_id=QJvmrm6D
