org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false

# Minecraft / NeoForge
minecraft_version=26.1.2
neoforge_version=26.1.2.22-beta

# Mod properties
mod_version=1.3.0
maven_group=com.breakinblocks.neosync
archives_base_name=NeoSync
mod_id=neosync
mod_author=BreakinBlocks

# Dependencies
mixinextras_version=0.4.1

# Integration deps
jei_version=29.5.0.26
jade_version=26.1.1+neoforge
curios_version=15.0.0+26.1.2

# Publishing
curseforge_project_id=1521718
modrinth_project_id=QJvmrm6D
