modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="neosync"
version="${version}"
displayName="NeoSync"
authors="BreakinBlocks"
description='''One mind. Many bodies.'''
logoFile="assets/neosync/icon.png"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[mixins]]
config="neosync.mixins.json"

[[dependencies.neosync]]
modId="neoforge"
type="required"
versionRange="[21.1,22)"
ordering="NONE"
side="BOTH"

[[dependencies.neosync]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"

[[dependencies.neosync]]
modId="jei"
type="optional"
versionRange="[19,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.neosync]]
modId="jade"
type="optional"
versionRange="[15,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.neosync]]
modId="curios"
type="optional"
versionRange="[9,)"
ordering="AFTER"
side="BOTH"

[[dependencies.neosync]]
modId="sable"
type="optional"
versionRange="[1.2,)"
ordering="AFTER"
side="BOTH"

[[dependencies.neosync]]
modId="mekanism"
type="optional"
versionRange="[10.7,)"
ordering="AFTER"
side="BOTH"
