modLoader="javafml"
loaderVersion="[11,)"
license="MIT"

[[mods]]
modId="neosync"
version="${version}"
displayName="NeoSync"
authors="BreakinBlocks"
description='''One mind. Many bodies.'''
logoFile="assets/neosync/icon.png"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[mixins]]
config="neosync.mixins.json"

[[dependencies.neosync]]
modId="neoforge"
type="required"
versionRange="[26.1,27)"
ordering="NONE"
side="BOTH"

[[dependencies.neosync]]
modId="minecraft"
type="required"
versionRange="[26.1,27)"
ordering="NONE"
side="BOTH"

[[dependencies.neosync]]
modId="jei"
type="optional"
versionRange="[19,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.neosync]]
modId="jade"
type="optional"
versionRange="[15,)"
ordering="AFTER"
side="CLIENT"
